# Generated by Django 4.0.6 on 2022-07-16 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=30)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
                ('skill', models.TextField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('interesting_keyword', models.TextField(null=True)),
                ('like_place', models.TextField(null=True)),
                ('unnlike_place', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
