# Generated by Django 4.0.6 on 2022-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_profile_interesting_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interesting_keyword',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_place',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unlike_place',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
