# Generated by Django 4.0.6 on 2022-07-22 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0007_topic_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='my_date_time_field',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_mate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
