# Generated by Django 4.0.6 on 2022-07-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_remove_schedule_my_date_time_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='my_date_field',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='my_time_field',
            field=models.TimeField(),
        ),
    ]
