# Generated by Django 4.0.6 on 2022-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0005_alter_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_do',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_emd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_sgg',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
