# Generated by Django 4.0.6 on 2022-07-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0006_user_address_do_user_address_emd_user_address_sgg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='residence',
        ),
    ]
