# Generated by Django 4.0.6 on 2022-07-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0007_remove_user_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(null=True),
        ),
    ]
