# Generated by Django 4.0.6 on 2022-07-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0009_alter_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='unnlike_place',
            new_name='unlike_place',
        ),
    ]
