# Generated by Django 4.0.6 on 2022-07-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0012_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo',
            new_name='photo',
        ),
    ]
