# Generated by Django 4.0.6 on 2022-07-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0013_rename_profile_photo_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interesting_keyword',
        ),
        migrations.RemoveField(
            model_name='user',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unlike_place',
        ),
    ]
