# Generated by Django 4.1 on 2022-08-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_user1_alter_room_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(db_column='room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.room'),
        ),
    ]
