# Generated by Django 4.1 on 2022-08-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.OneToOneField(db_column='room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.room'),
        ),
    ]
