# Generated by Django 4.1 on 2022-08-18 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_message_author_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sort',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=10, null=True)),
                ('number', models.PositiveIntegerField()),
                ('user1', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.CASCADE, related_name='thema1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.CASCADE, related_name='thema2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
