# Generated by Django 4.1 on 2022-08-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_sort_thema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemaMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.message')),
                ('thema_sort', models.CharField(max_length=10, null=True)),
                ('number', models.PositiveIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
            bases=('chat.message',),
        ),
    ]
