# Generated by Django 4.1 on 2022-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_thema_message_thema_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='promise_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
